---
title: "Exam 1"
author: "MAT 117"
date: "9/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Directions

This is exam totals *** points.  The value of each problem is indicated by the number for the problem.

You may have a half-sheet of notes for this exam.  You may use a calculator, Geogebra or Excel to aid in answering these problems.  You may not have any other windows open on your computer during the exam.  **Close them now.** You may also not communicate with anyone other than Rissler during the exam.  Failure to obey these directions are grounds for a 0 on this exam.

Write your answers on the paper provided and not on this exam, unless otherwise indicated.  Please label your answers clearly and provide sufficient reasoning that Rissler can follow your work.  Good luck!


## Questions

1.  Let $N$ be the number of eggs that a chicken has laid in its life.  Consider $N$ as a function $m$ the number of months the chicken has been alive.  For the first 5 months of a chicken's life it does not lay any eggs. During its 6th month alive it starts laying eggs and by the end of that month it lays at a rate of 5 eggs a week.  The chicken lays at this rate until its 8th month when it gets really cold and laying slows to about two eggs a week.  In the chicken's 10th month it begins laying at a rate of  5 eggs a week again.

    a. How many eggs has the chicken laid after 5 months?
    
    
    b. How many weeks are in a month?
    
    
    c. What is the average rate of change in the number of eggs the chicken has laid over the first 5 months of its life?
    
    
    d. What is the average rate of change in the number of eggs the chicken has laid between months 7 and 11 of its life?
    
    e. Sketch a graph of $N(m)$. Label any interesting points and describe why you sketched what you did.
    
    
2.  Let $f(x) = \frac{4}{\sqrt(x-1)}.

    a.  What is $f(2)$?
    
    b.  When is $f(x)=1$?
    
    c.  What is the average rate of change of $f(x)$ between $x=2$ and $x=5$?
    
    d.  What is the average rate of change of $f(x)$ between $x=5$ and $x=17$?
    
    e.  Graph $f(x)$ and describe its rate of change and concavity.  How do your answers from c and d support this?
    
    f.  What is the domain of $f(x)$?
    
    
3.  The height of a basketball above the floor (in feet) can be modeled as $h(t)=-16t^2+20t+8$, where $t$ is the time in seconds since the ball was shot.

    a. At what height was the ball released from? (How many seconds since the ball was shot is it when the ball is shot?)
    
    b. Assuming the shot was an airball, when does it hit the floor?
    
    c. Assuming it went in on the way back down, when did it do so? (A basketball rim is 10 feet above the floor.)
    
    d. What is the highest height that the ball achieves?
    
    
4. The table below gives the day in September and the height of the Mississippi River at Lock and Dam 11 in Dubuque is given in the table below.  Use it to answer the following questions.

    Day of September        | 5    | 10   | 15    | 20    | 25    |
    ------------------------|------|------|-------|-------|-------|
    Height of the river (ft)| 6.71 | 6.74 | 10.02 | 13.61 | 13.23 |
    
    a. Find the regression line that models the height of the river as a function of the day in September.  Record the equation.
    
    b. Describe what the numbers and variables in your equation mean.  Include units.
    
    c. What does your model predict was the height of the river on August 31?
    
    d. Flood stage at Dubuque is 16 feet.  When does your model predict that the Mississippi will be at flood stage in Dubuque?
    
    e. 

